# Habilitar o conversor Analógico-Digital (ADC)
CONFIG_ADC=y

# Configurações de Log
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y

# Otimização de velocidade e suporte a ponto flutuante (para o FIR, se usar floats)
CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Aumentar tamanho da pilha das threads devido ao uso do `printk` e `LOG`
CONFIG_MAIN_STACK_SIZE=2048